#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 06:00:00
#SBATCH -J job_name
#SBATCH --mail-type=ALL
#SBATCH --mail-user ksolander@me.com
#SBATCH --reservation=uppmax2022-2-5_2

# Load modules
module load bioinfo-tools
module load spider
module load canu

# Your commands
# -p vad filen ska heta
# -d vart du vill lägga resultatet 

cd $HOME/GitHub/Genome-Analysis/INTERMEDIATE

canu -d $HOME/GitHub/Genome-Analysis/RESULTS/ASSEMBLY -p PACBIO_DNA_ASSEMBLY  genomeSize=2.7m  -pacbio $HOME/GitHub/Genome-Analysis/DATA/RAW/genomic_data/PacBio/*
